#cllud-config
ssh_authorized_keys:
        - sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiR+ULhotYyBQC2gD4GbLbZDHpQTySgfRyR22/CKWv0DVBYt3S7PLmrfMNHrZtBTrgsuQNnEq8HN5hnpmq3umFhk/xCR5HXhfb1Lha6pc2gnjAmJupDafPHQlrEVRnFzPXXYXXEXdRfotA9D1pT3/RqRNHxoP2G5aXIUGPexjIqsOyyYCg35KQJeH67gaMnWinjW6lpTYK90sQTpW22XSu25vhWZ67YAFCUTrckpjBPvlaRyxgUQgAEqtcBcFvBuWLgMKI7ijJmg0+LUsH1FIpDRaoSojRWh0Spl+6KhNKQCetJhS0VqOnnCt9Pokvy75zX9huZXwY8LAJAHJ6ml5p dn@stack01.newtonium.local
